// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"
)

type Amm struct {
	AmmID         int64  `json:"amm_id"`
	DexName       string `json:"dex_name"`
	Fee           string `json:"fee"`
	RouterAddress string `json:"router_address"`
	AlgorithmType string `json:"algorithm_type"`
}

type Pool struct {
	Address     string    `json:"address"`
	AmmID       int64     `json:"amm_id"`
	TokenA      string    `json:"token_a"`
	TokenB      string    `json:"token_b"`
	ReserveA    string    `json:"reserve_a"`
	ReserveB    string    `json:"reserve_b"`
	TotalValue  string    `json:"total_value"`
	LastUpdated time.Time `json:"last_updated"`
}

type Token struct {
	Address   string    `json:"address"`
	Name      string    `json:"name"`
	Symbol    string    `json:"symbol"`
	Decimals  int32     `json:"decimals"`
	Base      bool      `json:"base"`
	Native    bool      `json:"native"`
	Ticker    string    `json:"ticker"`
	Price     string    `json:"price"`
	CreatedAt time.Time `json:"created_at"`
}
