// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"context"
)

type Querier interface {
	CreateAmm(ctx context.Context, arg CreateAmmParams) (Amm, error)
	CreatePool(ctx context.Context, arg CreatePoolParams) (Pool, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	DeleteAmm(ctx context.Context, ammID int64) error
	DeletePool(ctx context.Context, poolID int64) error
	DeleteToken(ctx context.Context, address string) error
	GetAllAmms(ctx context.Context) ([]Amm, error)
	GetAllPools(ctx context.Context) ([]Pool, error)
	GetAllPoolsWithoutKeys(ctx context.Context) ([]Pool, error)
	GetAllTokens(ctx context.Context) ([]Token, error)
	GetAllTokensWithTickers(ctx context.Context) ([]Token, error)
	GetAmmByDEX(ctx context.Context, dexName string) ([]Amm, error)
	GetAmmById(ctx context.Context, ammID int64) (Amm, error)
	GetAmmKeys(ctx context.Context) ([]string, error)
	GetBaseTokens(ctx context.Context) ([]Token, error)
	GetHashedIndexerPwd(ctx context.Context) (string, error)
	GetIndexerStatus(ctx context.Context) (Indexer, error)
	GetKeys(ctx context.Context) ([]string, error)
	GetNativeTokens(ctx context.Context) ([]Token, error)
	GetPoolByAddress(ctx context.Context, address string) (Pool, error)
	GetPoolByAddressExtra(ctx context.Context, arg GetPoolByAddressExtraParams) (Pool, error)
	GetPoolsByAmm(ctx context.Context, ammID int64) ([]Pool, error)
	GetPoolsByPair(ctx context.Context, arg GetPoolsByPairParams) ([]Pool, error)
	GetPoolsByToken(ctx context.Context, tokenA string) ([]Pool, error)
	GetTokenAPriceByPool(ctx context.Context, poolID int64) (string, error)
	GetTokenBPriceByPool(ctx context.Context, poolID int64) (string, error)
	GetTokenByAddress(ctx context.Context, address string) (Token, error)
	GetTokenBySymbol(ctx context.Context, symbol string) (Token, error)
	InitIndexer(ctx context.Context, arg InitIndexerParams) (Indexer, error)
	UpdateBaseNativeStatus(ctx context.Context, arg UpdateBaseNativeStatusParams) (Token, error)
	UpdateIndexerStatus(ctx context.Context, arg UpdateIndexerStatusParams) (Indexer, error)
	UpdatePoolExtraData(ctx context.Context, arg UpdatePoolExtraDataParams) (Pool, error)
	UpdatePoolFee(ctx context.Context, arg UpdatePoolFeeParams) (Pool, error)
	UpdatePoolGeneralExtraData(ctx context.Context, arg UpdatePoolGeneralExtraDataParams) (Pool, error)
	UpdatePoolReserves(ctx context.Context, arg UpdatePoolReservesParams) (Pool, error)
	UpdatePoolReservesWithExtraData(ctx context.Context, arg UpdatePoolReservesWithExtraDataParams) (Pool, error)
	UpdatePoolTV(ctx context.Context, arg UpdatePoolTVParams) (Pool, error)
	UpdatePrice(ctx context.Context, arg UpdatePriceParams) (Token, error)
	UpdateTicker(ctx context.Context, arg UpdateTickerParams) (Token, error)
}

var _ Querier = (*Queries)(nil)
